import { CryptoCard } from './types';
import { Zap, TrendingUp, TrendingDown, Shield } from 'lucide-react';

export const INITIAL_HP = 100;

export const ICONS = {
  Zap: () => <Zap className="w-4 h-4" />,
  TrendingUp: () => <TrendingUp className="w-4 h-4" />,
  TrendingDown: () => <TrendingDown className="w-4 h-4" />,
  Shield: () => <Shield className="w-4 h-4" />,
};

export const CRYPTO_CARDS: CryptoCard[] = [
  {
    id: 'btc',
    name: 'Bitcoin',
    symbol: 'BTC',
    type: 'BLUE_CHIP',
    power: 25,
    stability: 20,
    flavorText: 'The OG. Number go up technology.',
    color: 'bg-gradient-to-br from-orange-500 to-amber-600',
  },
  {
    id: 'eth',
    name: 'Ethereum',
    symbol: 'ETH',
    type: 'LAYER_1',
    power: 22,
    stability: 18,
    flavorText: 'Ultra sound money. Maybe.',
    color: 'bg-gradient-to-br from-indigo-500 to-purple-600',
  },
  {
    id: 'sol',
    name: 'Solana',
    symbol: 'SOL',
    type: 'LAYER_1',
    power: 20,
    stability: 12,
    flavorText: 'Fast, cheap, and only 48% uptime.',
    color: 'bg-gradient-to-br from-purple-500 to-teal-400',
  },
  {
    id: 'doge',
    name: 'Dogecoin',
    symbol: 'DOGE',
    type: 'MEME',
    power: 15,
    stability: 5,
    flavorText: 'Much wow. Very volatility.',
    color: 'bg-gradient-to-br from-yellow-400 to-amber-500',
  },
  {
    id: 'pepe',
    name: 'Pepe',
    symbol: 'PEPE',
    type: 'MEME',
    power: 30,
    stability: 2,
    flavorText: 'Feels good man. Until it doesn\'t.',
    color: 'bg-gradient-to-br from-green-500 to-emerald-600',
  },
  {
    id: 'usdc',
    name: 'USD Coin',
    symbol: 'USDC',
    type: 'STABLECOIN',
    power: 5,
    stability: 25,
    flavorText: 'Boring. But at least it\'s backed.',
    color: 'bg-gradient-to-br from-blue-400 to-blue-600',
  },
  {
    id: 'uni',
    name: 'Uniswap',
    symbol: 'UNI',
    type: 'DEFI',
    power: 18,
    stability: 14,
    flavorText: 'The OG DEX. Fees are a feature.',
    color: 'bg-gradient-to-br from-pink-500 to-rose-600',
  },
  {
    id: 'aave',
    name: 'Aave',
    symbol: 'AAVE',
    type: 'DEFI',
    power: 16,
    stability: 16,
    flavorText: 'Borrow against your JPEGs.',
    color: 'bg-gradient-to-br from-cyan-400 to-purple-500',
  },
  {
    id: 'link',
    name: 'Chainlink',
    symbol: 'LINK',
    type: 'BLUE_CHIP',
    power: 17,
    stability: 15,
    flavorText: 'Oracles. Marines. $1000 EOY.',
    color: 'bg-gradient-to-br from-blue-500 to-indigo-600',
  },
  {
    id: 'matic',
    name: 'Polygon',
    symbol: 'MATIC',
    type: 'LAYER_1',
    power: 14,
    stability: 13,
    flavorText: 'L2? Sidechain? Yes.',
    color: 'bg-gradient-to-br from-purple-600 to-violet-700',
  },
  {
    id: 'shib',
    name: 'Shiba Inu',
    symbol: 'SHIB',
    type: 'MEME',
    power: 28,
    stability: 3,
    flavorText: 'The DOGE killer. Or is it?',
    color: 'bg-gradient-to-br from-orange-400 to-red-500',
  },
  {
    id: 'avax',
    name: 'Avalanche',
    symbol: 'AVAX',
    type: 'LAYER_1',
    power: 19,
    stability: 14,
    flavorText: 'Subnets go brrrr.',
    color: 'bg-gradient-to-br from-red-500 to-rose-600',
  },
];
